# Example secret configuration for different deployment scenarios

# Scenario 1: Auto-detection (Recommended for production)
# The controller will automatically detect and use the best available backend
apiVersion: v1
kind: ConfigMap
metadata:
  name: nhn-controller-config
  namespace: k-paas-system
data:
  secret-config.yaml: |
    secret:
      name: "nhncloud-credentials"
      management:
        mode: "auto"  # OpenBao -> ESO -> Kubernetes (fallback)
        
        openbao:
          address: "http://openbao.openbao-system.svc.cluster.local:8200"
          path: "secret/data/k-paas/nhn-controller"
          role: "nhn-controller"
          namespace: "openbao-system"
        
        eso:
          externalSecretName: "nhncloud-credentials-external"
          secretStoreName: "aws-secrets-manager"
          timeout: "5m"
        
        kubernetes:
          namespace: "k-paas-system"

---
# Scenario 2: Force Kubernetes Secret only (Development/Testing)
apiVersion: v1
kind: ConfigMap
metadata:
  name: nhn-controller-config-dev
  namespace: k-paas-system
data:
  secret-config.yaml: |
    secret:
      name: "nhncloud-credentials"
      management:
        mode: "kubernetes"  # Only use Kubernetes Secret
        
        kubernetes:
          namespace: "k-paas-system"

---
# Scenario 3: External Secrets Operator only (Production with AWS)
apiVersion: v1
kind: ConfigMap
metadata:
  name: nhn-controller-config-eso
  namespace: k-paas-system
data:
  secret-config.yaml: |
    secret:
      name: "nhncloud-credentials"
      management:
        mode: "eso"  # Only use External Secrets Operator
        
        eso:
          externalSecretName: "nhncloud-credentials-external"
          secretStoreName: "aws-secrets-manager"
          timeout: "5m"

---
# Environment variable configuration example
# These can be set in the deployment to override default values
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: k-paas-system
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        # Secret configuration overrides
        - name: SECRET_NAME
          value: "nhncloud-credentials"
        - name: SECRET_MODE
          value: "auto"  # auto, kubernetes, openbao, eso
        
        # OpenBao specific configuration
        - name: OPENBAO_ADDRESS
          value: "http://openbao.openbao-system.svc.cluster.local:8200"
        - name: OPENBAO_PATH
          value: "secret/data/k-paas/nhn-controller"
        - name: OPENBAO_ROLE
          value: "nhn-controller"
        
        # ESO specific configuration
        - name: ESO_EXTERNAL_SECRET_NAME
          value: "nhncloud-credentials-external"
        
        # Controller namespace (important for secret detection)
        - name: CONTROLLER_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace